# This is a basic workflow to help you get started with Actions

name: New Issue Handling

# Controls when the workflow will run
on:
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.4.3
      - run: echo "${{ JSON.stringify(steps.parse.outputs.data) }}"
